### model
model_name: qwen2_5_vl
method: retake
attn_implementation: "flash_attention_2"

### dataset
dataset_name: videomme
anno_file: dataset/video_mme/video_mme.json
dataloader_num_workers: 4

### data
sample_fps: 2
max_num_frames: 256
longsize_resolution: 448

### generate
do_sample: false

### output
output_dir: results/qwen2_5_vl_7b_videomme_f256_2fps_r448/base
